// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, name, slug, icon, description, order_index)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, icon, description, order_index, created_at
`

type CreateCategoryParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Icon        sql.NullString `json:"icon"`
	Description sql.NullString `json:"description"`
	OrderIndex  sql.NullInt32  `json:"order_index"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Description,
		arg.OrderIndex,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, icon, description, order_index, created_at FROM categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, icon, description, order_index, created_at FROM categories
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, icon, description, order_index, created_at FROM categories
ORDER BY order_index ASC, name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Description,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    icon = COALESCE($4, icon),
    description = COALESCE($5, description),
    order_index = COALESCE($6, order_index)
WHERE id = $1
RETURNING id, name, slug, icon, description, order_index, created_at
`

type UpdateCategoryParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	Slug        sql.NullString `json:"slug"`
	Icon        sql.NullString `json:"icon"`
	Description sql.NullString `json:"description"`
	OrderIndex  sql.NullInt32  `json:"order_index"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Description,
		arg.OrderIndex,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}
