// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type AppSetting struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type Category struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Icon        sql.NullString `json:"icon"`
	Description sql.NullString `json:"description"`
	OrderIndex  sql.NullInt32  `json:"order_index"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Recipe struct {
	ID                uuid.UUID      `json:"id"`
	Title             string         `json:"title"`
	Slug              string         `json:"slug"`
	MarkdownContent   string         `json:"markdown_content"`
	AuthorID          uuid.NullUUID  `json:"author_id"`
	CategoryID        uuid.NullUUID  `json:"category_id"`
	Description       sql.NullString `json:"description"`
	PrepTimeMinutes   sql.NullInt32  `json:"prep_time_minutes"`
	CookTimeMinutes   sql.NullInt32  `json:"cook_time_minutes"`
	Servings          sql.NullInt32  `json:"servings"`
	Difficulty        sql.NullString `json:"difficulty"`
	FeaturedImagePath sql.NullString `json:"featured_image_path"`
	IsPublished       sql.NullBool   `json:"is_published"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	PublishedAt       sql.NullTime   `json:"published_at"`
}

type RecipeGroup struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type RecipeGrouping struct {
	GroupID    uuid.UUID     `json:"group_id"`
	RecipeID   uuid.UUID     `json:"recipe_id"`
	OrderIndex sql.NullInt32 `json:"order_index"`
}

type RecipeImage struct {
	ID            uuid.UUID      `json:"id"`
	RecipeID      uuid.NullUUID  `json:"recipe_id"`
	FilePath      string         `json:"file_path"`
	WebpPath      sql.NullString `json:"webp_path"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	Caption       sql.NullString `json:"caption"`
	OrderIndex    sql.NullInt32  `json:"order_index"`
	UploadedAt    sql.NullTime   `json:"uploaded_at"`
}

type RecipeTag struct {
	RecipeID uuid.UUID `json:"recipe_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

type ShareCode struct {
	ID        uuid.UUID     `json:"id"`
	RecipeID  uuid.NullUUID `json:"recipe_id"`
	Code      string        `json:"code"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
	MaxUses   sql.NullInt32 `json:"max_uses"`
	UseCount  sql.NullInt32 `json:"use_count"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type SharedRecipe struct {
	ID                uuid.UUID      `json:"id"`
	RecipeID          uuid.NullUUID  `json:"recipe_id"`
	SourceInstanceUrl sql.NullString `json:"source_instance_url"`
	SourceRecipeID    uuid.NullUUID  `json:"source_recipe_id"`
	Signature         string         `json:"signature"`
	ImportedAt        sql.NullTime   `json:"imported_at"`
}

type Tag struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Color     sql.NullString `json:"color"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type UserInvite struct {
	ID        uuid.UUID      `json:"id"`
	Code      string         `json:"code"`
	Email     sql.NullString `json:"email"`
	Role      sql.NullString `json:"role"`
	CreatedBy uuid.NullUUID  `json:"created_by"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
	UsedAt    sql.NullTime   `json:"used_at"`
	UsedBy    uuid.NullUUID  `json:"used_by"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
