// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRecipeToGroup(ctx context.Context, arg AddRecipeToGroupParams) error
	AddTagToRecipe(ctx context.Context, arg AddTagToRecipeParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateRecipeGroup(ctx context.Context, arg CreateRecipeGroupParams) (RecipeGroup, error)
	CreateRecipeImage(ctx context.Context, arg CreateRecipeImageParams) (RecipeImage, error)
	CreateShareCode(ctx context.Context, arg CreateShareCodeParams) (ShareCode, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) (UserInvite, error)
	CreateVariation(ctx context.Context, arg CreateVariationParams) (RecipeVariation, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteInvite(ctx context.Context, id uuid.UUID) error
	DeleteRecipe(ctx context.Context, id uuid.UUID) error
	DeleteRecipeGroup(ctx context.Context, id uuid.UUID) error
	DeleteRecipeImage(ctx context.Context, id uuid.UUID) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteShareCode(ctx context.Context, id uuid.UUID) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteVariation(ctx context.Context, id uuid.UUID) error
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetGroupsForRecipe(ctx context.Context, recipeID uuid.UUID) ([]RecipeGroup, error)
	GetInviteByCode(ctx context.Context, code string) (UserInvite, error)
	GetRecipeByID(ctx context.Context, id uuid.UUID) (Recipe, error)
	GetRecipeBySlug(ctx context.Context, slug string) (Recipe, error)
	GetRecipeGroupByID(ctx context.Context, id uuid.UUID) (RecipeGroup, error)
	GetRecipeGroupBySlug(ctx context.Context, slug string) (RecipeGroup, error)
	GetRecipeGroupWithRecipes(ctx context.Context, id uuid.UUID) (GetRecipeGroupWithRecipesRow, error)
	GetRecipeImageByID(ctx context.Context, id uuid.UUID) (RecipeImage, error)
	GetRecipeImages(ctx context.Context, recipeID uuid.NullUUID) ([]RecipeImage, error)
	GetRecipeTags(ctx context.Context, recipeID uuid.UUID) ([]Tag, error)
	GetRecipeWithImages(ctx context.Context, id uuid.UUID) (GetRecipeWithImagesRow, error)
	GetRecipesInGroup(ctx context.Context, groupID uuid.UUID) ([]Recipe, error)
	GetSetting(ctx context.Context, key string) (AppSetting, error)
	GetShareCodeByCode(ctx context.Context, code string) (GetShareCodeByCodeRow, error)
	GetShareCodesForRecipe(ctx context.Context, recipeID uuid.NullUUID) ([]ShareCode, error)
	GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error)
	GetTagBySlug(ctx context.Context, slug string) (Tag, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetVariationByID(ctx context.Context, id uuid.UUID) (RecipeVariation, error)
	GetVariationByRecipeAndAuthor(ctx context.Context, recipeID uuid.UUID, authorID uuid.UUID) (RecipeVariation, error)
	GetVariationsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]RecipeVariation, error)
	GetVariationsByRecipeWithAuthor(ctx context.Context, recipeID uuid.UUID) ([]GetVariationsByRecipeWithAuthorRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IncrementShareCodeUse(ctx context.Context, id uuid.UUID) error
	ListCategories(ctx context.Context) ([]Category, error)
	ListInvites(ctx context.Context) ([]UserInvite, error)
	ListRecipeGroups(ctx context.Context) ([]RecipeGroup, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error)
	ListVariationsByAuthor(ctx context.Context, arg ListVariationsByAuthorParams) ([]RecipeVariation, error)
	ListRecipesByAuthor(ctx context.Context, arg ListRecipesByAuthorParams) ([]Recipe, error)
	ListRecipesByCategory(ctx context.Context, arg ListRecipesByCategoryParams) ([]Recipe, error)
	ListSettings(ctx context.Context) ([]AppSetting, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveRecipeFromGroup(ctx context.Context, arg RemoveRecipeFromGroupParams) error
	RemoveTagFromRecipe(ctx context.Context, arg RemoveTagFromRecipeParams) error
	SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateRecipeFeaturedImage(ctx context.Context, arg UpdateRecipeFeaturedImageParams) (Recipe, error)
	UpdateRecipeGroup(ctx context.Context, arg UpdateRecipeGroupParams) (RecipeGroup, error)
	UpdateRecipeImage(ctx context.Context, arg UpdateRecipeImageParams) (RecipeImage, error)
	UpdateRecipePublishedStatus(ctx context.Context, arg UpdateRecipePublishedStatusParams) (Recipe, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVariation(ctx context.Context, arg UpdateVariationParams) (RecipeVariation, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (AppSetting, error)
	UseInvite(ctx context.Context, arg UseInviteParams) (UserInvite, error)
}

var _ Querier = (*Queries)(nil)
