// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipe_images.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRecipeImage = `-- name: CreateRecipeImage :one
INSERT INTO recipe_images (recipe_id, file_path, webp_path, thumbnail_path, caption, order_index)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, recipe_id, file_path, webp_path, thumbnail_path, caption, order_index, uploaded_at
`

type CreateRecipeImageParams struct {
	RecipeID      uuid.NullUUID  `json:"recipe_id"`
	FilePath      string         `json:"file_path"`
	WebpPath      sql.NullString `json:"webp_path"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	Caption       sql.NullString `json:"caption"`
	OrderIndex    sql.NullInt32  `json:"order_index"`
}

func (q *Queries) CreateRecipeImage(ctx context.Context, arg CreateRecipeImageParams) (RecipeImage, error) {
	row := q.db.QueryRowContext(ctx, createRecipeImage,
		arg.RecipeID,
		arg.FilePath,
		arg.WebpPath,
		arg.ThumbnailPath,
		arg.Caption,
		arg.OrderIndex,
	)
	var i RecipeImage
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.FilePath,
		&i.WebpPath,
		&i.ThumbnailPath,
		&i.Caption,
		&i.OrderIndex,
		&i.UploadedAt,
	)
	return i, err
}

const deleteRecipeImage = `-- name: DeleteRecipeImage :exec
DELETE FROM recipe_images WHERE id = $1
`

func (q *Queries) DeleteRecipeImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeImage, id)
	return err
}

const getRecipeImageByID = `-- name: GetRecipeImageByID :one
SELECT id, recipe_id, file_path, webp_path, thumbnail_path, caption, order_index, uploaded_at FROM recipe_images
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecipeImageByID(ctx context.Context, id uuid.UUID) (RecipeImage, error) {
	row := q.db.QueryRowContext(ctx, getRecipeImageByID, id)
	var i RecipeImage
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.FilePath,
		&i.WebpPath,
		&i.ThumbnailPath,
		&i.Caption,
		&i.OrderIndex,
		&i.UploadedAt,
	)
	return i, err
}

const getRecipeImages = `-- name: GetRecipeImages :many
SELECT id, recipe_id, file_path, webp_path, thumbnail_path, caption, order_index, uploaded_at FROM recipe_images
WHERE recipe_id = $1
ORDER BY order_index
`

func (q *Queries) GetRecipeImages(ctx context.Context, recipeID uuid.NullUUID) ([]RecipeImage, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeImages, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeImage
	for rows.Next() {
		var i RecipeImage
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.FilePath,
			&i.WebpPath,
			&i.ThumbnailPath,
			&i.Caption,
			&i.OrderIndex,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeWithImages = `-- name: GetRecipeWithImages :one
SELECT 
    r.id, r.title, r.slug, r.markdown_content, r.author_id, r.category_id, r.description, r.prep_time_minutes, r.cook_time_minutes, r.servings, r.difficulty, r.featured_image_path, r.is_published, r.created_at, r.updated_at, r.published_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', ri.id,
                'file_path', ri.file_path,
                'webp_path', ri.webp_path,
                'thumbnail_path', ri.thumbnail_path,
                'caption', ri.caption,
                'order_index', ri.order_index
            ) ORDER BY ri.order_index
        ) FILTER (WHERE ri.id IS NOT NULL), 
        '[]'::json
    ) as body_images
FROM recipes r
LEFT JOIN recipe_images ri ON r.id = ri.recipe_id
WHERE r.id = $1
GROUP BY r.id
`

type GetRecipeWithImagesRow struct {
	ID                uuid.UUID      `json:"id"`
	Title             string         `json:"title"`
	Slug              string         `json:"slug"`
	MarkdownContent   string         `json:"markdown_content"`
	AuthorID          uuid.NullUUID  `json:"author_id"`
	CategoryID        uuid.NullUUID  `json:"category_id"`
	Description       sql.NullString `json:"description"`
	PrepTimeMinutes   sql.NullInt32  `json:"prep_time_minutes"`
	CookTimeMinutes   sql.NullInt32  `json:"cook_time_minutes"`
	Servings          sql.NullInt32  `json:"servings"`
	Difficulty        sql.NullString `json:"difficulty"`
	FeaturedImagePath sql.NullString `json:"featured_image_path"`
	IsPublished       sql.NullBool   `json:"is_published"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	BodyImages        interface{}    `json:"body_images"`
}

func (q *Queries) GetRecipeWithImages(ctx context.Context, id uuid.UUID) (GetRecipeWithImagesRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeWithImages, id)
	var i GetRecipeWithImagesRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.MarkdownContent,
		&i.AuthorID,
		&i.CategoryID,
		&i.Description,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.Servings,
		&i.Difficulty,
		&i.FeaturedImagePath,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.BodyImages,
	)
	return i, err
}

const updateRecipeImage = `-- name: UpdateRecipeImage :one
UPDATE recipe_images
SET
    caption = COALESCE($2, caption),
    order_index = COALESCE($3, order_index)
WHERE id = $1
RETURNING id, recipe_id, file_path, webp_path, thumbnail_path, caption, order_index, uploaded_at
`

type UpdateRecipeImageParams struct {
	ID         uuid.UUID      `json:"id"`
	Caption    sql.NullString `json:"caption"`
	OrderIndex sql.NullInt32  `json:"order_index"`
}

func (q *Queries) UpdateRecipeImage(ctx context.Context, arg UpdateRecipeImageParams) (RecipeImage, error) {
	row := q.db.QueryRowContext(ctx, updateRecipeImage, arg.ID, arg.Caption, arg.OrderIndex)
	var i RecipeImage
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.FilePath,
		&i.WebpPath,
		&i.ThumbnailPath,
		&i.Caption,
		&i.OrderIndex,
		&i.UploadedAt,
	)
	return i, err
}
