// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipe_groups.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addRecipeToGroup = `-- name: AddRecipeToGroup :exec
INSERT INTO recipe_groupings (group_id, recipe_id, order_index)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, recipe_id) DO UPDATE SET order_index = $3
`

type AddRecipeToGroupParams struct {
	GroupID    uuid.UUID     `json:"group_id"`
	RecipeID   uuid.UUID     `json:"recipe_id"`
	OrderIndex sql.NullInt32 `json:"order_index"`
}

func (q *Queries) AddRecipeToGroup(ctx context.Context, arg AddRecipeToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeToGroup, arg.GroupID, arg.RecipeID, arg.OrderIndex)
	return err
}

const createRecipeGroup = `-- name: CreateRecipeGroup :one
INSERT INTO recipe_groups (id, name, slug, description, icon)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, description, icon, created_at
`

type CreateRecipeGroupParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
}

func (q *Queries) CreateRecipeGroup(ctx context.Context, arg CreateRecipeGroupParams) (RecipeGroup, error) {
	row := q.db.QueryRowContext(ctx, createRecipeGroup,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
	)
	var i RecipeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecipeGroup = `-- name: DeleteRecipeGroup :exec
DELETE FROM recipe_groups WHERE id = $1
`

func (q *Queries) DeleteRecipeGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeGroup, id)
	return err
}

const getGroupsForRecipe = `-- name: GetGroupsForRecipe :many
SELECT g.id, g.name, g.slug, g.description, g.icon, g.created_at 
FROM recipe_groups g
JOIN recipe_groupings rg ON g.id = rg.group_id
WHERE rg.recipe_id = $1
ORDER BY g.name
`

func (q *Queries) GetGroupsForRecipe(ctx context.Context, recipeID uuid.UUID) ([]RecipeGroup, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsForRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeGroup
	for rows.Next() {
		var i RecipeGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeGroupByID = `-- name: GetRecipeGroupByID :one
SELECT id, name, slug, description, icon, created_at FROM recipe_groups
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecipeGroupByID(ctx context.Context, id uuid.UUID) (RecipeGroup, error) {
	row := q.db.QueryRowContext(ctx, getRecipeGroupByID, id)
	var i RecipeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipeGroupBySlug = `-- name: GetRecipeGroupBySlug :one
SELECT id, name, slug, description, icon, created_at FROM recipe_groups
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetRecipeGroupBySlug(ctx context.Context, slug string) (RecipeGroup, error) {
	row := q.db.QueryRowContext(ctx, getRecipeGroupBySlug, slug)
	var i RecipeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipeGroupWithRecipes = `-- name: GetRecipeGroupWithRecipes :one
SELECT 
    g.id, g.name, g.slug, g.description, g.icon, g.created_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', r.id,
                'title', r.title,
                'slug', r.slug,
                'featured_image_path', r.featured_image_path,
                'description', r.description,
                'order_index', rg.order_index
            ) ORDER BY rg.order_index
        ) FILTER (WHERE r.id IS NOT NULL), 
        '[]'::json
    ) as recipes
FROM recipe_groups g
LEFT JOIN recipe_groupings rg ON g.id = rg.group_id
LEFT JOIN recipes r ON rg.recipe_id = r.id
WHERE g.id = $1
GROUP BY g.id
`

type GetRecipeGroupWithRecipesRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	Recipes     interface{}    `json:"recipes"`
}

func (q *Queries) GetRecipeGroupWithRecipes(ctx context.Context, id uuid.UUID) (GetRecipeGroupWithRecipesRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeGroupWithRecipes, id)
	var i GetRecipeGroupWithRecipesRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.Recipes,
	)
	return i, err
}

const getRecipesInGroup = `-- name: GetRecipesInGroup :many
SELECT r.id, r.title, r.slug, r.markdown_content, r.author_id, r.category_id, r.description, r.prep_time_minutes, r.cook_time_minutes, r.servings, r.difficulty, r.featured_image_path, r.is_published, r.created_at, r.updated_at, r.published_at 
FROM recipes r
JOIN recipe_groupings rg ON r.id = rg.recipe_id
WHERE rg.group_id = $1
  AND r.is_published = true
ORDER BY rg.order_index
`

func (q *Queries) GetRecipesInGroup(ctx context.Context, groupID uuid.UUID) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getRecipesInGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.MarkdownContent,
			&i.AuthorID,
			&i.CategoryID,
			&i.Description,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.Servings,
			&i.Difficulty,
			&i.FeaturedImagePath,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeGroups = `-- name: ListRecipeGroups :many
SELECT id, name, slug, description, icon, created_at FROM recipe_groups
ORDER BY created_at DESC
`

func (q *Queries) ListRecipeGroups(ctx context.Context) ([]RecipeGroup, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeGroup
	for rows.Next() {
		var i RecipeGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecipeFromGroup = `-- name: RemoveRecipeFromGroup :exec
DELETE FROM recipe_groupings
WHERE group_id = $1 AND recipe_id = $2
`

type RemoveRecipeFromGroupParams struct {
	GroupID  uuid.UUID `json:"group_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

func (q *Queries) RemoveRecipeFromGroup(ctx context.Context, arg RemoveRecipeFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeRecipeFromGroup, arg.GroupID, arg.RecipeID)
	return err
}

const updateRecipeGroup = `-- name: UpdateRecipeGroup :one
UPDATE recipe_groups
SET
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    icon = COALESCE($5, icon)
WHERE id = $1
RETURNING id, name, slug, description, icon, created_at
`

type UpdateRecipeGroupParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	Slug        sql.NullString `json:"slug"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
}

func (q *Queries) UpdateRecipeGroup(ctx context.Context, arg UpdateRecipeGroupParams) (RecipeGroup, error) {
	row := q.db.QueryRowContext(ctx, updateRecipeGroup,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
	)
	var i RecipeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}
