// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_codes.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createShareCode = `-- name: CreateShareCode :one
INSERT INTO share_codes (recipe_id, code, expires_at, max_uses)
VALUES ($1, $2, $3, $4)
RETURNING id, recipe_id, code, expires_at, max_uses, use_count, created_at
`

type CreateShareCodeParams struct {
	RecipeID  uuid.NullUUID `json:"recipe_id"`
	Code      string        `json:"code"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
	MaxUses   sql.NullInt32 `json:"max_uses"`
}

func (q *Queries) CreateShareCode(ctx context.Context, arg CreateShareCodeParams) (ShareCode, error) {
	row := q.db.QueryRowContext(ctx, createShareCode,
		arg.RecipeID,
		arg.Code,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i ShareCode
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Code,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShareCode = `-- name: DeleteShareCode :exec
DELETE FROM share_codes WHERE id = $1
`

func (q *Queries) DeleteShareCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShareCode, id)
	return err
}

const getShareCodeByCode = `-- name: GetShareCodeByCode :one
SELECT sc.id, sc.recipe_id, sc.code, sc.expires_at, sc.max_uses, sc.use_count, sc.created_at, r.title as recipe_title, r.slug as recipe_slug
FROM share_codes sc
JOIN recipes r ON sc.recipe_id = r.id
WHERE sc.code = $1
  AND (sc.expires_at IS NULL OR sc.expires_at > NOW())
  AND (sc.max_uses IS NULL OR sc.use_count < sc.max_uses)
LIMIT 1
`

type GetShareCodeByCodeRow struct {
	ID          uuid.UUID     `json:"id"`
	RecipeID    uuid.NullUUID `json:"recipe_id"`
	Code        string        `json:"code"`
	ExpiresAt   sql.NullTime  `json:"expires_at"`
	MaxUses     sql.NullInt32 `json:"max_uses"`
	UseCount    sql.NullInt32 `json:"use_count"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	RecipeTitle string        `json:"recipe_title"`
	RecipeSlug  string        `json:"recipe_slug"`
}

func (q *Queries) GetShareCodeByCode(ctx context.Context, code string) (GetShareCodeByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getShareCodeByCode, code)
	var i GetShareCodeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Code,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
		&i.RecipeTitle,
		&i.RecipeSlug,
	)
	return i, err
}

const getShareCodesForRecipe = `-- name: GetShareCodesForRecipe :many
SELECT id, recipe_id, code, expires_at, max_uses, use_count, created_at FROM share_codes
WHERE recipe_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetShareCodesForRecipe(ctx context.Context, recipeID uuid.NullUUID) ([]ShareCode, error) {
	rows, err := q.db.QueryContext(ctx, getShareCodesForRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareCode
	for rows.Next() {
		var i ShareCode
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Code,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementShareCodeUse = `-- name: IncrementShareCodeUse :exec
UPDATE share_codes
SET use_count = use_count + 1
WHERE id = $1
`

func (q *Queries) IncrementShareCodeUse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementShareCodeUse, id)
	return err
}
