// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addTagToRecipe = `-- name: AddTagToRecipe :exec
INSERT INTO recipe_tags (recipe_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToRecipeParams struct {
	RecipeID uuid.UUID `json:"recipe_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToRecipe(ctx context.Context, arg AddTagToRecipeParams) error {
	_, err := q.db.ExecContext(ctx, addTagToRecipe, arg.RecipeID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, slug, color)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, color, created_at
`

type CreateTagParams struct {
	ID    uuid.UUID      `json:"id"`
	Name  string         `json:"name"`
	Slug  string         `json:"slug"`
	Color sql.NullString `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getRecipeTags = `-- name: GetRecipeTags :many
SELECT t.id, t.name, t.slug, t.color, t.created_at FROM tags t
JOIN recipe_tags rt ON t.id = rt.tag_id
WHERE rt.recipe_id = $1
`

func (q *Queries) GetRecipeTags(ctx context.Context, recipeID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeTags, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, slug, color, created_at FROM tags
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug, color, created_at FROM tags
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, color, created_at FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromRecipe = `-- name: RemoveTagFromRecipe :exec
DELETE FROM recipe_tags
WHERE recipe_id = $1 AND tag_id = $2
`

type RemoveTagFromRecipeParams struct {
	RecipeID uuid.UUID `json:"recipe_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromRecipe(ctx context.Context, arg RemoveTagFromRecipeParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromRecipe, arg.RecipeID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    color = COALESCE($4, color)
WHERE id = $1
RETURNING id, name, slug, color, created_at
`

type UpdateTagParams struct {
	ID    uuid.UUID      `json:"id"`
	Name  sql.NullString `json:"name"`
	Slug  sql.NullString `json:"slug"`
	Color sql.NullString `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
