// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_invites.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserInvite = `-- name: CreateUserInvite :one
INSERT INTO user_invites (code, email, role, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, email, role, created_by, expires_at, used_at, used_by, created_at
`

type CreateUserInviteParams struct {
	Code      string         `json:"code"`
	Email     sql.NullString `json:"email"`
	Role      sql.NullString `json:"role"`
	CreatedBy uuid.NullUUID  `json:"created_by"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) (UserInvite, error) {
	row := q.db.QueryRowContext(ctx, createUserInvite,
		arg.Code,
		arg.Email,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM user_invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, code, email, role, created_by, expires_at, used_at, used_by, created_at FROM user_invites
WHERE code = $1
  AND (expires_at IS NULL OR expires_at > NOW())
  AND used_at IS NULL
LIMIT 1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (UserInvite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCode, code)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, code, email, role, created_by, expires_at, used_at, used_by, created_at FROM user_invites
ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]UserInvite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInvite
	for rows.Next() {
		var i UserInvite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Email,
			&i.Role,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useInvite = `-- name: UseInvite :one
UPDATE user_invites
SET
    used_at = NOW(),
    used_by = $2
WHERE id = $1
RETURNING id, code, email, role, created_by, expires_at, used_at, used_by, created_at
`

type UseInviteParams struct {
	ID     uuid.UUID     `json:"id"`
	UsedBy uuid.NullUUID `json:"used_by"`
}

func (q *Queries) UseInvite(ctx context.Context, arg UseInviteParams) (UserInvite, error) {
	row := q.db.QueryRowContext(ctx, useInvite, arg.ID, arg.UsedBy)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.CreatedAt,
	)
	return i, err
}
