// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVariation = `-- name: CreateVariation :one
INSERT INTO recipe_variations (id, recipe_id, author_id, markdown_content, prep_time_minutes, cook_time_minutes, servings, difficulty, notes, is_published)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING *
`

func (q *Queries) CreateVariation(ctx context.Context, arg CreateVariationParams) (RecipeVariation, error) {
	row := q.db.QueryRowContext(ctx, createVariation,
		arg.ID,
		arg.RecipeID,
		arg.AuthorID,
		arg.MarkdownContent,
		arg.PrepTimeMinutes,
		arg.CookTimeMinutes,
		arg.Servings,
		arg.Difficulty,
		arg.Notes,
		arg.IsPublished,
	)
	var i RecipeVariation
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.AuthorID,
		&i.MarkdownContent,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.Servings,
		&i.Difficulty,
		&i.Notes,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariationByID = `-- name: GetVariationByID :one
SELECT * FROM recipe_variations WHERE id = $1
`

func (q *Queries) GetVariationByID(ctx context.Context, id uuid.UUID) (RecipeVariation, error) {
	row := q.db.QueryRowContext(ctx, getVariationByID, id)
	var i RecipeVariation
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.AuthorID,
		&i.MarkdownContent,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.Servings,
		&i.Difficulty,
		&i.Notes,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariationsByRecipe = `-- name: GetVariationsByRecipe :many
SELECT * FROM recipe_variations
WHERE recipe_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetVariationsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]RecipeVariation, error) {
	rows, err := q.db.QueryContext(ctx, getVariationsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeVariation
	for rows.Next() {
		var i RecipeVariation
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.AuthorID,
			&i.MarkdownContent,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.Servings,
			&i.Difficulty,
			&i.Notes,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishedVariationsByRecipe = `-- name: GetPublishedVariationsByRecipe :many
SELECT * FROM recipe_variations
WHERE recipe_id = $1 AND is_published = true
ORDER BY created_at DESC
`

func (q *Queries) GetPublishedVariationsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]RecipeVariation, error) {
	rows, err := q.db.QueryContext(ctx, getPublishedVariationsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeVariation
	for rows.Next() {
		var i RecipeVariation
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.AuthorID,
			&i.MarkdownContent,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.Servings,
			&i.Difficulty,
			&i.Notes,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariationByRecipeAndAuthor = `-- name: GetVariationByRecipeAndAuthor :one
SELECT * FROM recipe_variations
WHERE recipe_id = $1 AND author_id = $2
`

func (q *Queries) GetVariationByRecipeAndAuthor(ctx context.Context, recipeID uuid.UUID, authorID uuid.UUID) (RecipeVariation, error) {
	row := q.db.QueryRowContext(ctx, getVariationByRecipeAndAuthor, recipeID, authorID)
	var i RecipeVariation
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.AuthorID,
		&i.MarkdownContent,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.Servings,
		&i.Difficulty,
		&i.Notes,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariation = `-- name: UpdateVariation :one
UPDATE recipe_variations
SET
    markdown_content = COALESCE($2, markdown_content),
    prep_time_minutes = COALESCE($3, prep_time_minutes),
    cook_time_minutes = COALESCE($4, cook_time_minutes),
    servings = COALESCE($5, servings),
    difficulty = COALESCE($6, difficulty),
    notes = COALESCE($7, notes),
    is_published = COALESCE($8, is_published),
    updated_at = NOW()
WHERE id = $1
RETURNING *
`

func (q *Queries) UpdateVariation(ctx context.Context, arg UpdateVariationParams) (RecipeVariation, error) {
	row := q.db.QueryRowContext(ctx, updateVariation,
		arg.ID,
		arg.MarkdownContent,
		arg.PrepTimeMinutes,
		arg.CookTimeMinutes,
		arg.Servings,
		arg.Difficulty,
		arg.Notes,
		arg.IsPublished,
	)
	var i RecipeVariation
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.AuthorID,
		&i.MarkdownContent,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.Servings,
		&i.Difficulty,
		&i.Notes,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVariation = `-- name: DeleteVariation :exec
DELETE FROM recipe_variations WHERE id = $1
`

func (q *Queries) DeleteVariation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVariation, id)
	return err
}

const listVariationsByAuthor = `-- name: ListVariationsByAuthor :many
SELECT * FROM recipe_variations
WHERE author_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListVariationsByAuthor(ctx context.Context, arg ListVariationsByAuthorParams) ([]RecipeVariation, error) {
	rows, err := q.db.QueryContext(ctx, listVariationsByAuthor,
		arg.AuthorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeVariation
	for rows.Next() {
		var i RecipeVariation
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.AuthorID,
			&i.MarkdownContent,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.Servings,
			&i.Difficulty,
			&i.Notes,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariationsByRecipeWithAuthor = `-- name: GetVariationsByRecipeWithAuthor :many
SELECT
	rv.*,
	u.email as author_email,
	u.role as author_role
FROM recipe_variations rv
JOIN users u ON rv.author_id = u.id
WHERE rv.recipe_id = $1
ORDER BY rv.created_at DESC
`

func (q *Queries) GetVariationsByRecipeWithAuthor(ctx context.Context, recipeID uuid.UUID) ([]GetVariationsByRecipeWithAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, getVariationsByRecipeWithAuthor, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVariationsByRecipeWithAuthorRow
	for rows.Next() {
		var i GetVariationsByRecipeWithAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.AuthorID,
			&i.MarkdownContent,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.Servings,
			&i.Difficulty,
			&i.Notes,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorEmail,
			&i.AuthorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
