// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type RecipeVariation struct {
	ID              uuid.UUID      `json:"id"`
	RecipeID        uuid.UUID      `json:"recipe_id"`
	AuthorID        uuid.UUID      `json:"author_id"`
	MarkdownContent string         `json:"markdown_content"`
	PrepTimeMinutes sql.NullInt32  `json:"prep_time_minutes"`
	CookTimeMinutes sql.NullInt32  `json:"cook_time_minutes"`
	Servings        sql.NullInt32  `json:"servings"`
	Difficulty      sql.NullString `json:"difficulty"`
	Notes           sql.NullString `json:"notes"`
	IsPublished     sql.NullBool   `json:"is_published"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type CreateVariationParams struct {
	ID              uuid.UUID      `json:"id"`
	RecipeID        uuid.UUID      `json:"recipe_id"`
	AuthorID        uuid.UUID      `json:"author_id"`
	MarkdownContent string         `json:"markdown_content"`
	PrepTimeMinutes sql.NullInt32  `json:"prep_time_minutes"`
	CookTimeMinutes sql.NullInt32  `json:"cook_time_minutes"`
	Servings        sql.NullInt32  `json:"servings"`
	Difficulty      sql.NullString `json:"difficulty"`
	Notes           sql.NullString `json:"notes"`
	IsPublished     sql.NullBool   `json:"is_published"`
}

type UpdateVariationParams struct {
	ID              uuid.UUID      `json:"id"`
	MarkdownContent sql.NullString `json:"markdown_content"`
	PrepTimeMinutes sql.NullInt32  `json:"prep_time_minutes"`
	CookTimeMinutes sql.NullInt32  `json:"cook_time_minutes"`
	Servings        sql.NullInt32  `json:"servings"`
	Difficulty      sql.NullString `json:"difficulty"`
	Notes           sql.NullString `json:"notes"`
	IsPublished     sql.NullBool   `json:"is_published"`
}

type ListVariationsByAuthorParams struct {
	AuthorID uuid.UUID `json:"author_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetVariationsByRecipeWithAuthorRow struct {
	ID              uuid.UUID      `json:"id"`
	RecipeID        uuid.UUID      `json:"recipe_id"`
	AuthorID        uuid.UUID      `json:"author_id"`
	MarkdownContent string         `json:"markdown_content"`
	PrepTimeMinutes sql.NullInt32  `json:"prep_time_minutes"`
	CookTimeMinutes sql.NullInt32  `json:"cook_time_minutes"`
	Servings        sql.NullInt32  `json:"servings"`
	Difficulty      sql.NullString `json:"difficulty"`
	Notes           sql.NullString `json:"notes"`
	IsPublished     sql.NullBool   `json:"is_published"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	AuthorEmail     string         `json:"author_email"`
	AuthorRole      string         `json:"author_role"`
}
